language: objective-c
xcode_workspace: Rennes.xcworkspace
xcode_scheme: Rennes
osx_image: xcode7
xcode_sdk: iphoneos9.0
script: xctool -project Rennes.xcodeproj -scheme Rennes build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

